--- 
management.endpoints.web.exposure.include: "*"
server: 
  port: 8084
spring: 
  application: 
    name: MicroServiceDemo
test: 
  count: 2255
  list: "nikhil,sachin,joseph"
  map: "{name:'Nikhil',age:'26',id:'2013699999'}"
  value: hello cloud test server
